add /utol/lecturers/forums
utelecon/utelecon.github.io pull request #1080
Opened 2024-05-25 11:30 UTC by syobonpastel

2024-07-16 12:25 UTC, femshima reviewed
途中までですが一旦投げます．

2024-07-17 00:03 UTC, femshima commented on src/pages/utol/lecturers/forums/index.md
> +- **メッセージ**：スレッド内の一つ一つの投稿のことです．メッセージには，タイトルや本文，添付ファイルを含めることができます．
タイトルを含めることができる，という表現に違和感があるのですが，良い代案が思いつきません．例えば「メッセージはタイトルと本文からなり，添付ファイルを含めることもできます．」みたいな感じでしょうか（しかし本文がないメッセージもあるのですよね…）．

2024-07-17 00:03 UTC, femshima commented on src/pages/utol/lecturers/forums/index.md
> +操作に必要な権限：担当教員・コース設計者・TA・履修者
brはHTMLタグで書いたほうがわかりやすいと思います．

2024-07-17 04:18 UTC, syobonpastel commented on src/pages/utol/lecturers/forums/index.md
> +- **スレッド**：テーマに対して立てられる話題ごとの枠組みです．一つのテーマに対して複数のスレッドを登録できます．なおテーマを新規に登録した場合，「デフォルトのスレッド」が生成されます．
「編集と削除だけ必要な権限が異なる」「自分が作ったもののみ編集可能」など操作が可能な条件が細かいので、まとめて書くとわかりにくいかなと思い、それぞれの操作に対応させて書いています。
またスレッドは、権限がややこしい機能の主たるものなので、簡単に説明するのは難しい気がします。（テーマの説明を変更する方が良いのかもしれないなと思いました。）

2024-07-17 04:30 UTC, femshima commented on src/pages/utol/lecturers/forums/index.md
> +- **スレッド**：テーマに対して立てられる話題ごとの枠組みです．一つのテーマに対して複数のスレッドを登録できます．なおテーマを新規に登録した場合，「デフォルトのスレッド」が生成されます．
であれば，テーマのところに権限の話を入れなくても良いかもしれません．

2024-07-21 09:24 UTC, syobonpastel commented on src/pages/utol/lecturers/forums/index.md
> +   - 投稿内容，添付ファイル，画像のいずれかの入力が必要です．タイトルのみの投稿はできません．
添付ファイルに画像は含められる一方で、[マークアップ](https://utelecon.adm.u-tokyo.ac.jp/utol/markup/#%E3%83%9E%E3%83%BC%E3%82%AF%E3%82%A2%E3%83%83%E3%83%97%E6%A9%9F%E8%83%BD%E5%AF%BE%E5%BF%9C%E3%81%AE%E3%83%86%E3%82%AD%E3%82%B9%E3%83%88%E3%82%A8%E3%83%AA%E3%82%A2%E3%81%AE%E8%A6%8B%E5%88%86%E3%81%91%E6%96%B9)のページの画像から想像するにありそうな、画像を本文中に含める機能が掲示板にはないのですよね……。指しているものが不明なので確認したいと思います。（エラーメッセージでいずれかが必要と出たのが、この文章の根拠ですね……。）
<img width="856" alt="image" src="https://github.com/user-attachments/assets/145ab58c-09d4-498f-9d10-d435d3bf3b6e">

2024-07-21 09:24 UTC, syobonpastel commented on src/pages/utol/lecturers/forums/index.md
> +   - [**表示ラベル**](../settings/#label)
利用しました。

2024-07-21 09:24 UTC, syobonpastel commented on src/pages/utol/lecturers/forums/index.md
> +- **メッセージ**：スレッド内の一つ一つの投稿のことです．メッセージには，タイトルや本文，添付ファイルを含めることができます．
その辺を考えると致し方ないような気もしてます。（タイトルは必須ではないのも難しいところだと感じています。）

2024-07-21 09:26 UTC, syobonpastel commented on src/pages/utol/lecturers/forums/index.md
> +- **スレッド**：テーマに対して立てられる話題ごとの枠組みです．一つのテーマに対して複数のスレッドを登録できます．なおテーマを新規に登録した場合，「デフォルトのスレッド」が生成されます．
テーマの部分の権限の補足を消しました。

2024-07-21 09:31 UTC, syobonpastel commented on src/pages/utol/lecturers/forums/index.md
> +一般的なメールよりもチャットに近い形式で，授業に関する質問のやりとりや，グループワークの議論、履修者同士での意見交換などに用いることができます．
書くとしたら「メッセージ機能は履修者同士や履修者と担当教員・TA間のやり取りに向いているもの対し，掲示板機能は履修者全体や履修者複数人からなるグループなどでのやり取りでの利用に向いています．」ぐらいですかね……

2024-07-21 10:05 UTC, femshima requested changes
確認ありがとうございます．コメントへの返信と，一つ追加を行いました．

2024-07-21 10:05 UTC, femshima commented on src/pages/utol/lecturers/forums/index.md
> +   - 投稿内容，添付ファイル，画像のいずれかの入力が必要です．タイトルのみの投稿はできません．
確かにエラーメッセージはそのような表記ですね…
（マークアップのところで画像を載せるのであれば，それは本文といえそうな気がしています．）

2024-07-21 10:05 UTC, femshima commented on src/pages/utol/lecturers/forums/index.md
> +一般的なメールよりもチャットに近い形式で，授業に関する質問のやりとりや，グループワークの議論、履修者同士での意見交換などに用いることができます．
なるほど，メッセージを使う人が少なそうなことを考えると書かなくても良い気がしてきました．
ただ，文中にスペースが入ってしまうので改行は削除するか，別の段落にしてください．

2024-07-26 22:20 UTC, femshima approved these changes

2024-07-28 01:24 UTC, femshima commented on src/pages/utol/lecturers/forums/index.md
> +   - 投稿内容，添付ファイル，画像のいずれかの入力が必要です．タイトルのみの投稿はできません．
d5414a8 のバージョンで良いと思います．

2024-07-31 23:33 UTC, merged