Add: /eccs/features/webdav
utelecon/utelecon.github.io pull request #1203
Opened 2024-09-26 05:04 UTC by seieric

2024-10-11 10:44 UTC, femshima reviewed
すぐ気づいたところだけですが，一旦レビューを出します．

2024-11-12 12:14 UTC, femshima requested changes

2024-11-12 12:14 UTC, femshima commented on src/pages/eccs/features/webdav/index.mdx
> +UTokyo Account やECCS利用権を所持していない人から，指定したフォルダにファイルを受け取ることができる機能です．公開期限やパスワードを設定することも可能です．
```suggestion
UTokyo AccountやECCS利用権を所持していない人から，指定したフォルダにファイルを受け取ることができる機能です．公開期限やパスワードを設定することも可能です．
```

2024-11-12 12:16 UTC, femshima approved these changes

2024-12-08 05:20 UTC, phenylshima requested changes
@seieric 進捗管理シートで指摘があったものです．修正をお願いします．

2024-12-08 05:20 UTC, phenylshima commented on src/pages/eccs/features/webdav/index.mdx
> +     - [https://davw03.ecc.u-tokyo.ac.jp/](https://davm01.ecc.u-tokyo.ac.jp/)
すみません，レビューで気づけませんでした．
```suggestion
     - [https://davw03.ecc.u-tokyo.ac.jp/](https://davw03.ecc.u-tokyo.ac.jp/)
```

2024-12-09 04:34 UTC, merged