add `/google/misc/localpart/`
utelecon/utelecon.github.io pull request #1240
Opened 2024-10-22 05:44 UTC by syobonpastel

2024-11-10 07:23 UTC, syobonpastel commented
ECCSクラウドメールのローカルパートの設定について、離席から4年以上後に戻ってきたら他のユーザに以前使っていたローカルパートを取られていたというケースが（実際にはかなり低い確率ながら）あり得ます。その点についてはレビューの時に記載の対応を確認することにしたいと思います。

2024-11-25 06:23 UTC, seieric requested changes
> ECCSクラウドメールのローカルパートの設定について、離席から4年以上後に戻ってきたら他のユーザに以前使っていたローカルパートを取られていたというケースが（実際にはかなり低い確率ながら）あり得ます。その点についてはレビューの時に記載の対応を確認することにしたいと思います。 

この部分とコメントした部分のみ確認いただきたいです。

2024-11-25 06:23 UTC, seieric commented on src/pages/google/misc/localpart/index.md
> +- すでに他のユーザが使用しているメールアドレスや，最近まで他のユーザが使用していたメールアドレスを設定することはできません．
他の記事ではユーザという表現が使われていないようなので「ユーザー」で統一したほうが良いと思います。

2024-11-25 06:23 UTC, seieric commented on src/pages/google/misc/localpart/index.md
> +- 管理上の理由により，"admin"など，特定の文字列は使用できません．
特に理由はないですが``で囲うほうが自然な気がします。

2024-11-25 11:04 UTC, seieric approved these changes

2024-11-27 06:10 UTC, merged