add /eccs/features/printing/ and etc.
utelecon/utelecon.github.io pull request #1280
Opened 2024-11-19 07:27 UTC by Ryocat

2024-11-19 07:29 UTC, Ryocat commented on src/pages/eccs/features/printing/index.mdx
> +</div>
#1274と同じ

2024-11-25 07:46 UTC, seieric requested changes

2024-11-25 07:46 UTC, seieric commented on src/pages/eccs/features/printing/index.mdx
> +ECCS2021では印刷機器としてRICOH社製の複合機（RICOH MP IMC3500/IMC3000）を提供しており，これをECCS複合機と呼びます．ECCS複合機には，料金の支払いが必要な一部の操作を実行するための，複合機操作端末と課金装置が附属しています．
附属図書館などの固有名詞以外の例で「附属」の利用例が見つからなかったので「付属」で良い気がします。

```suggestion
ECCS2021では印刷機器としてRICOH社製の複合機（RICOH MP IMC3500/IMC3000）を提供しており，これをECCS複合機と呼びます．ECCS複合機には，料金の支払いが必要な一部の操作を実行するための，複合機操作端末と課金装置が付属しています．
```

2024-11-25 07:46 UTC, seieric commented on src/pages/eccs/features/printing/index.mdx
> +ただし，一部の複合機ではコピー機能やスキャン機能が無効化されています．詳しくは次の表をごらんください．
```suggestion
ただし，一部の複合機ではコピー機能やスキャン機能が無効化されています．詳しくは次の表をご覧ください．
```

2024-11-25 07:46 UTC, seieric commented on src/pages/eccs/features/printing/index.mdx
> +このページでは，ECCSでの印刷方法や複合機の使い方について説明します．詳しくは「利用の手引き」の該当箇所も参照してください．
利用の手引きへのリンク漏れではないでしょうか？ここではリンクしないという方針であれば問題ないです。

2024-11-25 07:46 UTC, seieric commented on src/pages/eccs/features/printing/index.mdx
> +ECCS複合機で印刷を実行する方法のうち，ECCS端末から専用の仮想プリンタに印刷ジョブを送信する方法を，オンデマンドプリントと呼びます．ECCS2021では，この方法の他にもいくつかの印刷方法を提供しています．
### オンデマンドプリントにも同じ説明があるので、軽くまとめるだけでいかがでしょうか？
```suggestion
ECCS2021では，3つの印刷方法を提供しています．
- オンデマンドプリント
- IPP印刷
- Webアップロード印刷
```

2024-11-25 07:46 UTC, seieric commented on src/pages/eccs/features/printing/index.mdx
> +### webアップロード印刷
```suggestion
### Webアップロード印刷
```

2025-03-30 15:04 UTC, merged