add: `/en/utol/lecturers/assignments/`
utelecon/utelecon.github.io pull request #1336
Opened 2024-12-23 12:51 UTC by syobonpastel

2025-01-04 10:37 UTC, phenylshima requested changes
まず，意味に影響しないところです．

2025-01-04 10:37 UTC, phenylshima commented on src/pages/en/utol/lecturers/assignments/index.mdx
> +The assignment function allows you to provide assignments to enrolled students on UTOL and grade their submissions. You can set a specific deadline, and the submission date as well as the time can be
```suggestion
The assignment function allows you to provide assignments to enrolled students on UTOL and grade their submissions. You can set a specific deadline, and the submission date as well as the time can be recorded. In addition, you can configure whether or not late submissions are allowed and whether or not students can view each other's submissions.
```

2025-01-04 10:37 UTC, phenylshima commented on src/pages/en/utol/lecturers/assignments/index.mdx
> +  - It is suitable for assignments with a certain amount of content and structure, such as presentation slides and reports, or assignments including content other than text.
```suggestion
  - It is suitable for assignments with a certain amount of content and structure, such as presentation slides and reports, or assignments including contents other than text.
```

2025-01-04 10:37 UTC, phenylshima commented on src/pages/en/utol/lecturers/assignments/index.mdx
> +  - Select the submission method("Upload File", "Text directly input").
```suggestion
  - Select the submission method ("Upload File", "Text directly input").
```

2025-01-04 10:37 UTC, phenylshima commented on src/pages/en/utol/lecturers/assignments/index.mdx
> +    - This is detail feedback on an assignment.
```suggestion
    - This is detailed feedback on an assignment.
```

2025-01-04 10:37 UTC, phenylshima commented on src/pages/en/utol/lecturers/assignments/index.mdx
> +2. Enter "Grade", "Comment" and save the file.
これはあまり自信がありません．
```suggestion
2. Enter "Grade" and "Comment", and save the file.
```

2025-01-04 10:58 UTC, phenylshima reviewed
やや細かく見ていますので，採否はお任せします．

2025-01-04 10:58 UTC, phenylshima commented on src/pages/en/utol/lecturers/assignments/index.mdx
> +  - It is safer to leave the setting as "Enable", as the load will be concentrated on UTOL after the end of the submission period, and there is a possibility of arising problems such as submission fa
提出期限の「前後」はおそらく「近い」なのでnearにしてみました．
```suggestion
  - It is safer to leave the setting as "Enable", as the load will be concentrated on UTOL near the end of the submission period, and there is a possibility of arising problems such as submission failure.
```

2025-01-04 10:58 UTC, phenylshima commented on src/pages/en/utol/lecturers/assignments/index.mdx
> +   - e.g.: If the feedback file is for enrolled student A, it will be "`Feedback_A.pdf`". Place "`Feedback_A.pdf`" in the "Feedback" folder, and enter the "`Feedback_A.pdf`" in the "File name" field
theはなくて良い気がします．
```suggestion
   - e.g.: If the feedback file is for enrolled student A, it will be "`Feedback_A.pdf`". Place "`Feedback_A.pdf`" in the "Feedback" folder, and enter "`Feedback_A.pdf`" in the "File name" field in the row for enrolled student A.
```

2025-01-04 10:58 UTC, phenylshima commented on src/pages/en/utol/lecturers/assignments/index.mdx
> +### Items to Set Up Assignments
DeepLに投げると「課題設定項目」になるのですが，やや難しいように思います．
シンプルにAssignment Settingsとか，Settings for Assignmentsとかでも良いような気もします．

2025-01-04 12:13 UTC, syobonpastel commented on src/pages/en/utol/lecturers/assignments/index.mdx
> +2. Enter "Grade", "Comment" and save the file.
`Enter "Grade" and "Comment", then save the file.` としてみました。

2025-01-05 01:54 UTC, phenylshima approved these changes

2025-01-08 23:58 UTC, merged