20230620 en matlab
utelecon/utelecon.github.io pull request #735
Opened 2023-06-27 03:42 UTC by CHENSSR

The MD for Matlab(EN)

2023-06-27 06:26 UTC, halphy requested changes
レビューしましたのでご確認お願いします。

2023-06-27 06:26 UTC, halphy commented on en/Matlab/index.md
> +The University of Tokyo has introduced the software 「[MATLAB](https://jp.mathworks.com/products/matlab.html)」provided by MathWorks, and supports its use on individual terminals, on shared terminals f
`「`と`」`は欧文で使われない約物 (punctuation mark) なので、代わりに二重引用符 `"` を使ってください。

2023-06-27 06:26 UTC, halphy commented on en/Matlab/index.md
> +The University of Tokyo has introduced the software 「[MATLAB](https://jp.mathworks.com/products/matlab.html)」provided by MathWorks, and supports its use on individual terminals, on shared terminals f
（おそらく単なる差し替え忘れだと思うのですが）リンク先のページに英語版が存在する場合には、リンク先のURLを英語版に書き換えてください。
https://jp.mathworks.com/products/matlab.html → https://www.mathworks.com/products/matlab.html

2023-06-27 06:26 UTC, halphy commented on en/Matlab/index.md
> +            <li>Go to your <a href="https://jp.mathworks.com/mwaccount/">MathWorks account page and sign in．</li>
リンク先を英語版のものに置き換えてください。
https://jp.mathworks.com/mwaccount/ → https://www.mathworks.com/mwaccount/

2023-06-27 06:26 UTC, halphy commented on en/Matlab/index.md
> +→ see: [System Requirements and Supported Compilers](https://www.mathworks.com/support/requirements/previous-releases.html)
`→` は欧文では使わないでください（原稿では `→` なしになっていると思います）。

2023-06-27 06:26 UTC, halphy commented on en/Matlab/index.md
> +→<b>see: **[Joining an open workspace in UTokyo Slack](/en/slack/join)**</b>
`→` は削除してください。

2023-06-27 06:43 UTC, halphy commented on en/Matlab/index.md
> +→<b>see: **[Joining an open workspace in UTokyo Slack](/en/slack/join)**</b>
`**` は不要です（`<b>`〜`</b>`で太字になります）

2023-07-04 05:29 UTC, halphy approved these changes
修正内容を確認し、いくつか修正等を加えました。
- 閉じタグ`</b>`が残っていた部分を削除しました。
- 英語版ページから `/matlab/` に飛ぶリンクを `/en/matlab/` に書き換えました。

2023-07-12 01:13 UTC, takemar commented on en/faculty_members/index.md
> +Please refer to the **[UTokyo MATLAB Campus-Wide License](/en/matlab/)** page (in Japanese) for details on usage and technical support.
```suggestion
Please refer to the **[UTokyo MATLAB Campus-Wide License](/en/matlab/)** page for details on usage and technical support.
```

2023-07-12 04:43 UTC, merged