202308 storage google document
utelecon/utelecon.github.io pull request #814
Opened 2023-10-03 04:04 UTC by mfujita3

2023-10-03 05:57 UTC, halphy requested changes

2023-10-03 05:57 UTC, halphy commented on src/pages/google/document.md
> +ECCSクラウドメールでログインすると，容量が100GBまで無償で利用できるほか，東大のアカウントに限定した共有などの機能が使えるようになります．ECCSクラウドメールの使い方は，「[ECCSクラウドメール (Google Workspace)](/eccs_cloud_email/)」を参照してください．
この段落はこのページに必要でしょうか
全体として、`/drive` の記述に合わせているのかそうでないのかがはっきりしない書き方に見えます。
第1段落だけ残して残りは削除することを提案します。`/eccs_cloud_email/`へのリンクは`/drive` に倣って第1段落の`「ECCSクラウドメール」` につけましょう

2023-10-03 05:57 UTC, halphy commented on src/pages/google/document.md
> +Googleドキュメントのファイルは，Google独自の形式のファイルになります．Googleドキュメントは，Microsoft Wordの形式に変換することが可能であり，アップロードしたMicrosoft Office形式のファイルをGoogleのサービス上で編集することも可能です．ただし，完全な互換性があるわけではなく，Microsoft Word形式のファイルをGoogleドキュメント上で
`drive/#format` に飛ばしていますが、飛ばした先でそこまで情報量が増えていないので、うーん

2023-10-03 05:57 UTC, halphy commented on src/pages/google/document.md
> +Googleドキュメントの作成は，Googleドライブ上で行うことができます．[Googleドライブの利用手順](drive/#access)を参照し，ドキュメントの作成を行ってください．
飛ばすべきはむしろ `drive` の「## ファイルを作成する」ではないですか

2023-10-03 05:57 UTC, halphy commented on src/pages/google/document.md
> +Googleドキュメントはオンラインでドキュメントの作成，編集が行えるサービスです．Googleドライブ上に文章を保存するため，ファイルを共有することで複数人が共同で編集作業を行うこともできます．Googleドライブについての詳細は，[Googleドライブの説明ページ](drive/)を参照してください．
```
Googleドキュメントはオンラインでドキュメントの作成，編集が行えるサービスです．
```
「ドキュメント」って日常語として使っていいのか怪しくありませんか（「文書」とか？）

2023-10-03 05:57 UTC, halphy commented on src/pages/google/document.md
> +Googleドキュメントで作成した文書は共有することで，他のユーザーと共同編集を行うことができます．
「Googleドキュメントで作成した文書は」→「Googleドキュメントで作成した文書**を**」

2023-10-03 05:57 UTC, halphy commented on src/pages/google/document.md
> +### ドキュメントの書き方
歴史的経緯なのはわかりますが、やはり「こういう機能があっておすすめですよ！」というトーンで書かれているので、このセクションだけ浮いているように見えます
この内容を残すにしても、リード文で趣旨を説明する（「ここでは，Googleドキュメントを編集する際に役立つ機能を紹介します」など）などしてこのページの他の部分の記述とトーンを合わせることはできそうです

2023-10-03 05:57 UTC, halphy commented on src/pages/google/document.md
> +### ドキュメントの書き方
`### ドキュメントの編集`としたほうが、すぐ上の `### ドキュメントの作成` とトーンが揃ってよさそうです

2023-10-03 11:10 UTC, mfujita3 commented on src/pages/google/document.md
> +Googleドキュメントのファイルは，Google独自の形式のファイルになります．Googleドキュメントは，Microsoft Wordの形式に変換することが可能であり，アップロードしたMicrosoft Office形式のファイルをGoogleのサービス上で編集することも可能です．ただし，完全な互換性があるわけではなく，Microsoft Word形式のファイルをGoogleドキュメント上で
`[Google独自の形式のファイル](drive/#format)`とかですかね？

2023-10-03 11:14 UTC, mfujita3 commented on src/pages/google/document.md
> +Googleドキュメントの作成は，Googleドライブ上で行うことができます．[Googleドライブの利用手順](drive/#access)を参照し，ドキュメントの作成を行ってください．
Googleドライブを開くまでは`drive/#access`で，開いた後の作成手順は`drive/basic`にあるのでどちらに飛ばすのが良いか悩んでる部分です．

2023-10-03 11:19 UTC, mfujita3 commented on src/pages/google/document.md
> +### ドキュメントの書き方
元のページがなければおそらく書いていない内容ではあるので，消しても良い気はしていますが，簡単に触れつつ[Googleドキュメントのヘルプ](https://support.google.com/docs/answer/1663349?hl=ja&ref_topic=1361461&sjid=13925397630418395873-AP)に飛ばすとかもありですかね？

2023-10-04 06:21 UTC, halphy commented on src/pages/google/document.md
> +Googleドキュメントのファイルは，Google独自の形式のファイルになります．Googleドキュメントは，Microsoft Wordの形式に変換することが可能であり，アップロードしたMicrosoft Office形式のファイルをGoogleのサービス上で編集することも可能です．ただし，完全な互換性があるわけではなく，Microsoft Word形式のファイルをGoogleドキュメント上で
良いと思います

2023-10-04 06:22 UTC, halphy commented on src/pages/google/document.md
> +### ドキュメントの書き方
ありだとおもいます

2023-10-04 11:03 UTC, mfujita3 commented on src/pages/google/document.md
> +### ドキュメントの書き方
ヘルプに飛ばすように書き直しました．

2023-10-20 01:33 UTC, takemar commented on src/pages/google/document.md
> +### ドキュメントの書き方
（亀レスすみません）ん，消すのは勿体ないというか，ここがないとこのページを独立したページとして作る意味がかなり薄れる気がします（この部分を消さずに接合するためにこのページの作業をしたのだと認識していました）．残っている内容がだいたいGoogleドライブのページへの誘導になっていますし．

2023-10-20 02:00 UTC, mfujita3 commented on src/pages/google/document.md
> +### ドキュメントの書き方
戻しました

2023-10-24 00:52 UTC, merged