202310 breadcrumb
utelecon/utelecon.github.io pull request #833
Opened 2023-10-26 01:10 UTC by cm-ayf

2024-01-09 07:47 UTC, halphy commented on src/pages/en/utokyo_account/mfa/reregister_and_terminate.md
> +  title: Reregistering Verification Method and Terminating
Reregistering のほうは目的語が省略されておらず、Terminating のほうは省略されているので対称的でないように見えます
`Reregistering Verification Method and Terminating the Use` とか？

2024-01-09 07:47 UTC, halphy commented on src/pages/en/utokyo_vpn/macos.mdx
> +  title: on macOS devices
文頭を大文字にしてください（あるいは`on`を削除）

2024-01-09 07:47 UTC, halphy commented on src/pages/en/utokyo_vpn/windows.mdx
> +  title: on Windows devices
文頭を大文字にしてください（あるいは`on`を削除）

2024-01-09 07:47 UTC, halphy commented on src/pages/en/webex/create_events.md
> +  title: Setting up a Webex Webinar
兄弟ページに揃えるなら `Setting up a Webinar` でしょうか

2024-01-09 07:47 UTC, halphy commented on src/pages/en/zoom/create_room/date_and_time/index.md
> +  title: Scheduling Recurring
recurring は形容詞なので修飾先の名詞は省略できません
```suggestion
  title: Scheduling Recurring Meetings
```

2024-01-09 07:47 UTC, halphy commented on src/pages/zoom/create_room/date_and_time/index.md
> +  title: 複数回利用できる URL が変わらない会議室
```suggestion
  title: 複数回利用できる URL が変わらない会議室を予約する
```

2024-01-09 07:47 UTC, halphy commented on src/pages/zoom/usage/layout/index.md
> +  title: 画面のレイアウト
```suggestion
  title: ミーティング画面のレイアウト
```

2024-01-09 07:47 UTC, halphy commented on src/pages/zoom/usage/screen_sharing/security/index.md
> +  title: 許可と制限
```suggestion
  title: 画面共有の許可と制限
```

2024-01-18 23:18 UTC, cm-ayf commented on src/pages/zoom/usage/screen_sharing/security/index.md
> +  title: 許可と制限
ここは親ページが画面共有なのでいらない気がしています

2024-01-22 07:35 UTC, halphy commented on src/pages/zoom/usage/screen_sharing/security/index.md
> +  title: 許可と制限
確かにそうですね
取り下げます

2024-02-02 01:06 UTC, femshima requested changes

2024-02-05 11:46 UTC, takemar commented on src/pages/docs/guideline.md
> +  title: オンライン授業向けツールのガイドライン
```suggestion
  title: オンライン授業向けツールの利用ガイドライン
```

名前が書かれている（=その責任で出されている）文書なので，先頭の修飾はさておき，途中の語を省くのは好ましくないと思います．

2024-02-20 11:26 UTC, merged