20231108 en /utokyo vpn/iphone
utelecon/utelecon.github.io pull request #843
Opened 2023-11-08 03:50 UTC by YODA0514

英訳したファイル（/utokyo_vpn/iphone）をmd化しました。画像ファイル8個を含んでおり、それらの画像ファイルは「img」フォルダにアップロードしました。

2023-12-05 05:14 UTC, halphy requested changes

2023-12-05 05:14 UTC, halphy commented on src/pages/en/utokyo_vpn/iphone.mdx
> +**Step C:** Tap "Connections" on the screen after launching the application, and then tap "Add VPN Connection..." on the subsequent screen. The following screen will then appear. Tap the input field
```suggestion
**Step C:** Tap "Connections" on the screen after launching the application, and then tap "Add VPN Connection..." on the subsequent screen. The following screen will then appear. Tap the input field next to "Server Address" and enter **vpn1.adm.u-tokyo.ac.jp**.
```

さらに言えばなぜここが `` ` `` 〜 `` ` `` で囲まれていないのか謎です（日英ともに）。特に理由がなければ追加したい

2023-12-18 00:23 UTC, halphy approved these changes

2024-01-15 00:46 UTC, TomokiHirota commented
最初にadd files via updateでファイルを上げた時に，ルートディレクトリにutokyo_vpn_iphoneが追加されてしまっているみたいですね．その後別途iphone.mdxが作られていると思われますので，utokyo_vpn_iphoneの方は削除します．

2024-01-15 07:59 UTC, merged