Astro v4
utelecon/utelecon.github.io pull request #891
Opened 2024-01-20 07:34 UTC by cm-ayf

2024-03-05 02:29 UTC, femshima requested changes
`<small>（新入生向け）</small>` など，フッターのsmallタグが効いていません（無視されています）．

2024-03-05 06:47 UTC, cm-ayf commented
fixed

2024-03-09 05:03 UTC, femshima commented
diff scriptで変更点を確認しました．最初の2つは特に問題ないと思います．

- footnoteから本文に戻るaria-labelが`Back to content`から`Back to reference 4`になっています．
- シンタックスハイライト周りで変更があったようです．
- `'`が自動的に`’`に変換される挙動がなくなっているようです（`en/notice` 2020-03-30など）．
- ocのように，見出しとid指定の間に1行入っているページのid指定が効かなくなっています．
- `dist/faculty_members/materials/VR_center_VRWebConf.pdf.html`等のファイルで，ほとんど空のhtmlが出力されています．

2024-03-14 23:32 UTC, cm-ayf commented
そうだった、Block IALは本来間の空行を許さないらしい仕様を真面目に実装したんだった
これまで使っていたBlockIALPluginはその辺り無頓着だったもので……

2024-03-18 07:48 UTC, femshima requested changes

2024-03-18 07:48 UTC, femshima commented on src/pages/oc/index.mdx
> +### UTokyo Microsoft License (Microsoft 365)
どこかの変更が紛れ込んでいませんか？

2024-03-18 07:48 UTC, femshima commented on src/pages/en/utokyo_wifi/index.mdx
> +### Connect Configuration
下の方に別のexpirationがあるので，おそらく手動での修正が必要です．

2024-03-18 07:52 UTC, femshima commented on src/pages/oc/index.mdx
> +### UTokyo Microsoft License (Microsoft 365)
`(Microsoft 365)`が追加されています．

2024-03-18 07:55 UTC, femshima approved these changes

2024-03-29 05:46 UTC, haxibami commented on .github/workflows/astro.yml
> +          node-version: 20
ここの変更とあわせて、READMEで指定する Node.js のバージョンも v20 に上げたほうがよい気がします

https://github.com/utelecon/utelecon.github.io/blob/23775e0b18b7b1f1b4e58cff3c5011e75108892c/README.md?plain=1#L9

2024-03-29 05:49 UTC, cm-ayf commented on .github/workflows/astro.yml
> +          node-version: 20
:done:

2024-03-29 06:01 UTC, merged