modify structure of utokyo_wifi/index page
utelecon/utelecon.github.io pull request #990
Opened 2024-03-21 12:03 UTC by takemar

2024-07-28 01:52 UTC, femshima commented on src/styles/components/lists.scss
> +    margin-left: 40px;
これはUAのstyleが`padding-inline-start: 40px`になっているだけなので，危ないと思います．
一つの方法として，`padding-inline-start`をuteleconのスタイルシートで明示的に指定し，SCSSの変数で共通化するというのはありかもしれません．

2024-08-22 08:47 UTC, femshima approved these changes

2024-08-24 11:21 UTC, femshima requested changes

2024-10-20 23:03 UTC, cm-ayf commented
<details>
<summary>/utokyo_wifi/ の diff</summary>

標準設定の prettier にかけた上で diff り，空行やCSSのリンク変更などを取り除いています．

```diff
341,342c341,347
<                       <a href="#connect-configuration" class="astro-rqztaddk"
<                         >接続の詳細な設定</a
---
>                       <a href="#apply" class="astro-rqztaddk"
>                         >準備編：UTokyo Wi-Fiアカウントの発行を申請する</a
>                       >
>                     </li>
>                     <li class="astro-rqztaddk">
>                       <a href="#connect" class="astro-rqztaddk"
>                         >利用編：UTokyo Wi-Fiに実際に接続する</a
343a349,371
>                       <ul class="toc-h4 astro-rqztaddk">
>                         <li class="astro-rqztaddk">
>                           <a
>                             href="#procedure-by-device-type"
>                             class="astro-rqztaddk"
>                             >端末の種類ごとの詳しい接続手順</a
>                           >
>                         </li>
>                         <li class="astro-rqztaddk">
>                           <a
>                             href="#procedure-by-device-type"
>                             class="astro-rqztaddk"
>                             >端末の種類別の詳しい接続手順</a
>                           >
>                         </li>
>                         <li class="astro-rqztaddk">
>                           <a
>                             href="#connect-configuration"
>                             class="astro-rqztaddk"
>                             >接続の詳細な設定</a
>                           >
>                         </li>
>                       </ul>
```
この PR の旨となる構造の変更を反映した toc の変更です．

```diff
491,494c519,522
<             また，UTokyo
<             Wi-Fiは，各個人が占有して利用する機器でのみ利用可能で，<strong>複数人が共用する機器での利用は禁止です</strong>．共用機器での利用は，UTokyo
<             Wi-Fiアカウントを取得した本人以外に利用させることになり，利用規程で禁止されているアカウントの貸与にあたるためです．なお，OSのユーザーアカウントが個人別に設定されていて，UTokyo
<             Wi-Fiアカウントを取得した本人以外が利用できない，という状況であれば問題ありません．
---
>             なお，UTokyo
>             Wi-Fiは，各個人が専有して利用する機器でのみ利用可能で，<strong>複数人が共用する機器での利用は禁止です</strong>．共用機器での利用は，UTokyo
>             Wi-Fiアカウントを取得した本人以外に利用させることになり，利用規程で禁止されているアカウントの貸与にあたるためです．ただし，OSのユーザーアカウントが個人別に設定されていて，UTokyo
>             Wi-Fiアカウントが取得した本人以外に利用できない，という状況であれば問題ありません．
```
ここは文言の修正が入った箇所です．

```diff
657,662c685,689
<           <ul>
<             <li>
<               この作業はキャンパス内のUTokyo
<               Wi-Fi（SSIDが<code>0000UTokyo</code>となっているWi-Fi）が見える場所でしかできません．
<             </li>
<           </ul>
---
> 
>           <p class="additional-info">
>             この作業はキャンパス内のUTokyo
>             Wi-Fi（SSIDが<code>0000UTokyo</code>となっているWi-Fi）が見える場所でしかできません．
>           </p>
```
ここは今回新たに導入したマークアップ改善です．

```diff
665c692,693
<               利用する機器のWi-Fi接続設定画面で，<code>0000UTokyo</code>を選んでください．
---
>               UTokyo
>               Wi-Fiに接続したい機器のWi-Fi接続設定画面で，<code>0000UTokyo</code>を選んでください．
```
文言修正です．

```diff
670c698
<               Accountではありません）．ユーザーIDとパスワードは，準備編の操作で届く通知メールから確認できるほか，申請直後であればアカウントメニューの申請完了画面にも表示されています．
---
>               Accountではありません）．ユーザーIDとパスワードは，上の「準備編」で届く通知メールから確認できるほか，申請直後であればアカウントメニューの申請完了画面にも表示されています．
```
見出しの変更に伴う文言修正です．

```diff
687a716,719
>           <h4 id="procedure-by-device-type">端末の種類ごとの詳しい接続手順</h4>
>           <p>
>             以下の各ページで，端末の種類ごとに詳しい接続手順を説明しています．
>           </p>
703c735
<           <h3 id="connect-configuration">接続の詳細な設定</h3>
---
>           <h4 id="connect-configuration">接続の詳細な設定</h4>
```
場所と見出しレベルの変更があります．

</details>

2024-10-26 07:06 UTC, femshima approved these changes

2024-10-31 00:21 UTC, merged